backend/app_sample/urls.py
from flask import Blueprint
bp = Blueprint('sample', __name__, cli_group=None, url_prefix='/')
from . import views

backend/proj/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

backend/app_sample/models.py
from django.db import models

# Create your models here.

backend/app_sample/views.py
from pprint import pprint
import feedparser
from flask import request, url_for, render_template, abort, redirect
from .urls import bp


feeds = {
    "https://blog.teclado.com/rss": {
        "title": "Teclado",
        "href": "https://blog.teclado.com/rss",
        "show_images": True,
        "entries": {},
    },
    "https://www.joshwcomeau.com/rss.xml": {
        "title": "Josh Comeau",
        "href": "https://www.joshwcomeau.com/rss.xml",
        "show_images": False,
        "entries": {},
    },
    # "https://snarky.ca/rss": {
    #     "title": "Snarky",
    #     "href": "https://snarky.ca/rss",
    #     "show_images": False,
    #     "entries": {},
    # },
}

@bp.route("/login", methods=["GET"])
def login():
    return render_template("login.html")

# Create your views here.
@bp.route("", endpoint="homepage", methods=["GET"])
@bp.route("/feed/<path:feed_url>", methods=["GET"])
def render_feed(feed_url: str = None):
    print(request.environ.get('user'))
    for url, feed_ in feeds.items():
        if feed_["entries"]:
            pass
        else:
            parsed_feed = feedparser.parse(url)
            for entry in parsed_feed.entries:
                if entry.link not in feed_["entries"]:
                    feed_["entries"][entry.link] = {**entry, "read": False}

    if feed_url is None:
        feed = list(feeds.values())[0]
    elif feed_url in feeds:
        if feed_url == list(feeds.keys())[0]:
            return redirect(url_for("sample.homepage"))
        else:
            feed = feeds[feed_url]
    else:
        return redirect(url_for("sample.homepage"))
    return render_template("feed.html", feeds=feeds, feed=feed)


@bp.route("/entries/<path:feed_url>", methods=["GET"])
def render_feed_entries(feed_url: str):
    try:
        feed = feeds[feed_url]
    except KeyError:
        abort(400)
    page = int(request.args.get("page", 0))
    entries = list(feed["entries"].values())[page * 5 : (page + 1) * 5]
    href = feed["href"]
    max_page = len(feed["entries"]) // 5

    return render_template(
        "partials/entry_page.html",
        entries=entries,
        href=href,
        page=page,
        max_page=max_page,
    )


@bp.route("/add_feed", methods=["POST"])
def add_feed():
    post_data = request.json if request.is_json else request.form
    feeds[post_data.get("href")] = {
        **post_data,
        "entries": {},
    }
    return redirect(url_for("sample.render_feed", feed_url=post_data.get("href")))


# @bp.route("/render_add_feed", methods=["GET"])
# def render_add_feed():
#     return render_template("partials/add_feed.html")


@bp.route("feed/<path:feed_url>/entry/<path:entry_url>", methods=["GET"])
def read_entry(feed_url: str, entry_url: str):
    try:
        feed = feeds[feed_url]
        entry = feed["entries"][entry_url]
        entry["read"] = True
    except KeyError:
        abort(400)
    return redirect(entry_url)

backend/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Blog</title>
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.14.1/dist/cdn.min.js"></script>
    <script src="https://unpkg.com/htmx.org@2.0.2" integrity="sha384-Y7hw+L/jvKeWIRRkqWYfPcvVxHzVzn5REgzbawhxAuQGwX1XWe70vji+VSeHOThJ" crossorigin="anonymous"></script>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body x-data>
    {% block content %}{% endblock %}
  </body>
</html>

backend/templates/feed.html
{% extends 'base.html' %} {% block content %}
<div class="hidden lg:fixed lg:inset-y-0 lg:flex lg:w-72 lg:flex-col">
  <div class="flex grow flex-col gap-y-5 overflow-y-auto bg-white px-6 py-4">
    <nav class="flex flex-1 flex-col">
      <ul role="list" class="flex flex-1 flex-col gap-y-3">
        {% for feed_url, feed_ in feeds.items() %}
        <li>
          <a
            href="{{ url_for('sample.render_feed', feed_url=feed_['href']) }}"
            hx-boost="true"
            class="{{'bg-green-700 text-white' if feed.href == feed_.href else ''}} flex gap-x-3 rounded-md p-2 text-sm font-semibold"
            >{{feed_['title']}}
            <span
              @read.window="{{'$el.innerHTML -= 1' if feed.href == feed_.href else ''}}"
              >{{ feed_['entries'].values() | rejectattr("read") | list | length
              }}</span
            >
          </a>
        </li>
        {% endfor %}
      </ul>
    </nav>
    <div
      x-data="{ show: false }"
      class="flex flex-col justify-center items-center"
    >
      <div x-show="show">{{ render_partial("partials/add_feed.html") }}</div>
      <button
        @click="show = !show"
        class="bg-slate-600 text-white font-semibold rounded-md px-4 py-2"
        x-text="show ? 'Hide' : 'Show'"
      ></button>
      {#<button
        hx-get="{{url_for('sample.render_add_feed')}}"
        hx-target="this"
        hx-swap="outerHTML"
        class="bg-slate-600 text-white font-semibold rounded-md px-4 py-2"
      >
        Add</button
      >#}
    </div>
  </div>
</div>

<div class="pl-72">
  <main class="py-10">
    <div
      class="px-4 sm:px-6 lg:px-8"
      id="entries"
      hx-get="{{url_for('sample.render_feed_entries', feed_url=feed['href']) }}"
      hx-trigger="load"
      hx-target="this"
      hx-swap="afterbegin"
    ></div>
    {# {{ render_partial("partials/entry_page.html",
    entries=list(feed['entries'].values())[0:5], href=feed['href'], page=0,
    max_page=10) }} #} {# {% for item in feed["entries"].values() %} {{
    render_partial("partials/entry.html", title=item.title,
    published=item.published, summary=item.summary,
    media_content=item.media_content, author=item.author, link=item.link) }} {%
    endfor %}#}
  </main>
</div>

{% endblock %}

backend/templates/login.html
{% extends "base.html" %}

{% block content %}
<!-- <form class="max-w-md mx-auto p-4 bg-white rounded-lg shadow-lg" action="{{ url_for('sample.login') }}" method="post">
    <h1 class="text-3xl font-bold">Login</h1>
    <div class="mt-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="username">Username</label>
        <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="username" type="text" name="username" required>
    </div>
    <div class="mt-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="password">Password</label>
        <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="password" type="password" name="password" required>
    </div>
    <div class="mt-4">
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" type="submit">Login</button>
    </div>
</form> -->

<aside class="fixed top-0 left-0 h-screen w-64 border-r border-b border-l border-gray-200 bg-white">
    <div class="h-16 px-4 flex items-center justify-center">
        <h1 class="text-2xl font-bold text-gray-900">Navigation</h1>
    </div>
    <ul class="mt-4 space-y-2">
        <li>
            <a href="{{ url_for('sample.login') }}" class="flex items-center px-4 py-2 text-gray-900 hover:bg-gray-200">
                <svg class="h-6 w-6 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path>
                </svg>
                <span>Home</span>
            </a>
        </li>
        <li>
            <a href="{{ url_for('sample.login') }}" class="flex items-center px-4 py-2 text-gray-900 hover:bg-gray-200">
                <svg class="h-6 w-6 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path>
                </svg>
                <span>Blog</span>
            </a>
        </li>
        <li>
            <a href="{{ url_for('sample.login') }}" class="flex items-center px-4 py-2 text-gray-900 hover:bg-gray-200">
                <svg class="h-6 w-6 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                </svg>
                <span>About</span>
            </a>
        </li>
    </ul>
</aside>

{% endblock %}

backend/templates/partials/add_feed.html
<form class="flex flex-col items-center" action="/add_feed" method="POST" hx-boost="true">
  <div>
    <label for="href">URL</label>
    <input type="text" id="href" name="href" class="bg-slate-100 p-2 mb-2" />
  </div>
  <div>
    <label for="title">Title</label>
    <input
      type="text"
      id="title"
      name="title"
      class="bg-slate-100 p-2 mb-2"
    />
  </div>
  <div>
    <label for="show_images">Show images</label>
    <input
      type="checkbox"
      id="show_images"
      name="show_images"
      class="bg-slate-100 p-2 mb-2"
    />
  </div>
  <input type="submit" value="Add" class="bg-slate-600 text-white font-semibold rounded-md px-4 py-2">
</form>

backend/templates/partials/entry.html
{# A summarized entry: - title - published - summary - media_content - author -
link - read #}
<article class="grid grid-cols-[300px_600px] mb-4">
  {% if media_content %}
  <img src="{{ media_content[0]['url']}}" alt="" />
  {% endif %}
  <div
    x-data="{ read: {{ read | lower }} }"
    class="ml-8 pt-4 {{'col-start-2' if media_content else 'col-start-1 col-span-2'}}"
  >
    <h2 class="font-bold text-2x1">
      <svg
        x-show="!read"
        viewBox="0 0 16 16"
        xmlns="http://www.w3.org/2000/svg"
        class="fill-emerald-500 h-3 w-3 inline-block mb-1"
      >
        <circle cx="8" cy="8" r="8" />
      </svg>
      {{title}}
    </h2>
    <p>
      Published by <span class="font-medium">{{author}}</span> {%if published
      %} on <span class="font-medium">{{published}}</span> {%endif%}
    </p>
    <p class="leading-6 mb-2">{{summary }}</p>
    <a
      @click="$dispatch('read', {}); read = true"
      href="{{url_for('sample.read_entry', feed_url=feed_url, entry_url=link)}}"
      class="underline"
      target="_blank"
      >Read article</a
    >
  </div>
</article>

backend/templates/partials/entry_page.html
{# - entries - page - max_page - href #} {% for item in entries %} {{
render_partial("partials/entry.html", title=item.title,
published=item.published, summary=item.summary,
media_content=item.media_content, author=item.author, link=item.link,
read=item.read, feed_url=href) }} {% endfor %} {% if page < max_page - 1 %}
<button
  hx-get="{{ url_for('sample.render_feed_entries', feed_url=href, page=page+1)}}"
  hx-swap="outerHTML"
  hx-target="this"
>
  Load more
</button>
{% endif %}